server:
  port: 9002

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resource-server:
        jwt:
          # 资源服务器获取到token之后要去授权服务器进行解析token
          issuer-uri: http://spring-oauth-server:9000
